import { LevelDefinition } from "../types/gameTypes";

export const levelBedroom: LevelDefinition = {
  id: "messy-bedroom-001",
  title: "Trini's Room",
  roomAssetKey: "room_bedroom_placeholder",
  worldWidth: 980,
  worldHeight: 1480,
  timeLimitSeconds: 50,
  inspector: {
    characterAssetKey: "character_mother_placeholder",
    arrivalSoundKey: "sfx_mother_arrival",
    screamSoundKey: "sfx_scream"
  },
  messItems: [
    {
      id: "crumbs-desk",
      label: "Desk Crumbs",
      messType: "dry_dirt",
      requiredTool: "vacuum",
      x: 440,
      y: 230,
      width: 130,
      height: 80,
      assetKey: "mess_crumbs",
      cleanProgressRequired: 90,
      scoreValue: 100,
      roomAssociation: "desk"
    },
    {
      id: "dust-under-bed",
      label: "Dust Drift",
      messType: "dry_dirt",
      requiredTool: "vacuum",
      x: 80,
      y: 340,
      width: 160,
      height: 76,
      assetKey: "mess_dust",
      cleanProgressRequired: 110,
      scoreValue: 125,
      roomAssociation: "bed"
    },
    {
      id: "snack-bits-door",
      label: "Snack Bits",
      messType: "dry_dirt",
      requiredTool: "vacuum",
      x: 320,
      y: 1220,
      width: 148,
      height: 90,
      assetKey: "mess_debris",
      cleanProgressRequired: 100,
      scoreValue: 110,
      roomAssociation: "door"
    },
    {
      id: "juice-rug",
      label: "Juice Puddle",
      messType: "wet_spill",
      requiredTool: "mop",
      x: 200,
      y: 840,
      width: 176,
      height: 124,
      assetKey: "mess_juice",
      cleanProgressRequired: 120,
      scoreValue: 140,
      roomAssociation: "rug"
    },
    {
      id: "mud-window",
      label: "Muddy Prints",
      messType: "wet_spill",
      requiredTool: "mop",
      x: 720,
      y: 680,
      width: 158,
      height: 120,
      assetKey: "mess_mud",
      cleanProgressRequired: 130,
      scoreValue: 150,
      roomAssociation: "window"
    },
    {
      id: "sticky-nightstand",
      label: "Mystery Sticky",
      messType: "wet_spill",
      requiredTool: "mop",
      x: 858,
      y: 390,
      width: 76,
      height: 76,
      assetKey: "mess_sticky",
      cleanProgressRequired: 115,
      scoreValue: 130,
      roomAssociation: "nightstand"
    },
    {
      id: "clothes-volcano",
      label: "Clothes Volcano",
      messType: "pickup",
      requiredTool: "hand",
      x: 360,
      y: 620,
      width: 180,
      height: 140,
      assetKey: "mess_clothes",
      cleanProgressRequired: 80,
      scoreValue: 115,
      roomAssociation: "floor"
    },
    {
      id: "toy-ambush",
      label: "Toy Ambush",
      messType: "pickup",
      requiredTool: "hand",
      x: 560,
      y: 900,
      width: 188,
      height: 120,
      assetKey: "mess_toys",
      cleanProgressRequired: 95,
      scoreValue: 125,
      roomAssociation: "rug"
    },
    {
      id: "trash-bedside",
      label: "Trash Nest",
      messType: "pickup",
      requiredTool: "hand",
      x: 650,
      y: 380,
      width: 160,
      height: 120,
      assetKey: "mess_trash",
      cleanProgressRequired: 85,
      scoreValue: 115,
      roomAssociation: "bedside"
    }
  ]
};
